name: Ping API

on:
  push:
    branches:
      - master  # O la rama en la que estás trabajando

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a ping request to the API
        run: curl -s -o /dev/null -w "%{http_code}" https://api-scrapping-news-rd.onrender.com/api/hoy
